# arduino makefile

	BOARD_TAG	= uno
	ARDUINO_PORT	= /dev/ttyACM0

	ARDUINO_LIBS = OneWire DallasTemperature LiquidCrystal_I2C SPI Ethernet EEPROM Wire Wire/utility

	include /usr/share/arduino/Arduino.mk
